FROM python:3.11

RUN mkdir /service
RUN mkdir /service/app
WORKDIR /service/app

COPY authentication/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./authentication/app /service/app
